imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        prefix_image: "/BoilerBox"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Lci\BoilerBoxBundle\Entity\User
    registration:
        form:
            type: 'Lci\BoilerBoxBundle\Form\Type\RegistrationFormType'
        confirmation:
            enabled: true
            from_email: 
                # Expediteur
                address: 'admin_ipc@cargo-france.fr'
                # Nom de l'expediteur
                sender_name: 'Administrateur BoilerBox'
            template: '@FOSUser/Registration/email.txt.twig'
    resetting:
        email: 
            from_email:
                # Expediteur
                address: 'admin_ipc@cargo-france.fr'
                # Nom de l'expediteur
                sender_name: 'Administrateur BoilerBox'
            template: '@FOSUser/Resetting/email.txt.twig'
    change_password:
        form: 
            type: 'Lci\BoilerBoxBundle\Form\Type\ChangePasswordFormType'
    from_email:
        address: "Assistance@lci-group.fr"
        sender_name: "Administrateur BoilerBox"

sensio_framework_extra:
   router:
        annotations: false

assetic:
    debug: "%kernel.debug%"
    use_controller: "%kernel.debug%"
